# Generated by Django 3.0.3 on 2020-03-05 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20200304_0924'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restaurant_data',
            name='name',
            field=models.CharField(max_length=200, unique=True),
        ),
    ]
