# Generated by Django 3.0.3 on 2020-03-05 12:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20200305_1241'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Restaurant_data',
            new_name='Restaurant_names',
        ),
    ]
