# Generated by Django 3.0.3 on 2020-03-08 08:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20200305_1255'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='restaurant',
            name='closing_time',
        ),
        migrations.RemoveField(
            model_name='restaurant',
            name='opening_time',
        ),
    ]
