# Generated by Django 3.0.3 on 2020-03-08 08:12

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_auto_20200308_0810'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurant',
            name='closing_time',
            field=django.contrib.postgres.fields.jsonb.JSONField(default=dict),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='opening_time',
            field=django.contrib.postgres.fields.jsonb.JSONField(default=dict),
        ),
    ]
