# Generated by Django 3.0.3 on 2020-03-08 08:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_auto_20200308_0812'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='restaurant',
            name='day',
        ),
    ]
