# Generated by Django 3.0.3 on 2020-03-10 13:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_collections_restaurantcollections_usercollections'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='restaurantcollections',
            unique_together={('restaurant_collection', 'restaurant')},
        ),
    ]
