# Generated by Django 3.0.3 on 2020-03-10 14:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_auto_20200310_1359'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Collections',
        ),
    ]
